# Generated by Django 2.0.3 on 2019-04-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('roomID', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('avail', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
