# Generated by Django 2.0.3 on 2019-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0002_auto_20190406_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
