# Generated by Django 2.0.3 on 2019-04-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0003_auto_20190406_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookID', models.IntegerField(primary_key=True, serialize=False)),
                ('agenda', models.TextField()),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('capacity', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isWifi', models.BooleanField()),
                ('isVid', models.BooleanField()),
                ('isProjector', models.BooleanField()),
                ('isBoard', models.BooleanField()),
                ('isAudio', models.BooleanField()),
                ('isAC', models.BooleanField()),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='facilities',
            name='roomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_room_booking.Rooms'),
        ),
    ]
