# Generated by Django 2.2 on 2019-04-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0004_auto_20190406_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='avail',
        ),
        migrations.AddField(
            model_name='bookings',
            name='roomID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meeting_room_booking.Rooms'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='bookID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='isAC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='isAudio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='isBoard',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='isProjector',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='isVid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='isWifi',
            field=models.IntegerField(),
        ),
    ]
