# Generated by Django 2.2 on 2019-04-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0005_auto_20190407_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.TextField(default='null', max_length=20),
        ),
    ]
