# Generated by Django 2.2 on 2019-04-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='null')),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_room_booking.Bookings')),
            ],
            options={
                'db_table': 'cancellations',
            },
        ),
    ]
