# Generated by Django 2.2 on 2019-04-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0009_cancellations'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meeting_room_booking.Employee'),
        ),
    ]
