# Generated by Django 2.2 on 2019-04-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0010_bookings_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='username',
            field=models.ForeignKey(default='aseem', on_delete=django.db.models.deletion.CASCADE, to='meeting_room_booking.Employee'),
        ),
    ]
