# Generated by Django 2.2 on 2019-04-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room_booking', '0011_auto_20190408_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='capacity',
        ),
    ]
